// Demo page actions
export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const INCREASE_COUNTER_LATER = 'INCREASE_COUNTER_LATER';

// Task page actions
export const SORT_FEATURE_TABLE_BY_CATEGORY = 'SORT_FEATURE_TABLE_BY_CATEGORY';
export const FILTER_FEATURE_TABLE = 'FILTER_FEATURE_TABLE';
export const RESET_FEATURE_TABLE = 'RESET_FEATURE_TABLE';
export const SORT_BUG_TABLE_BY_CATEGORY = 'SORT_BUG_TABLE_BY_CATEGORY';
export const FILTER_BUG_TABLE = 'FILTER_BUG_TABLE';
export const RESET_BUG_TABLE = 'RESET_BUG_TABLE';
export const FETCH_BUG_REQUEST = 'FETCH_BUG_REQUEST';
export const FETCH_BUG_SUCCESS = 'FETCH_BUG_SUCCESS';
export const FETCH_FEATURE_SUCCESS = 'FETCH_FEATURE_SUCCESS';
export const TASK_API_FAILURE = 'TASK_API_FAILURE';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';

export const EDIT_ETA_REQUEST = 'EDIT_ETA_REQUEST';
export const EDIT_ETA_SUCCESS = 'EDIT_ETA_SUCCESS';
