// Demo page actions
export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const INCREASE_COUNTER_LATER = 'INCREASE_COUNTER_LATER';

// Main actions
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const API_FAILURE = 'API_FAILURE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';

// Task page actions
export const SORT_FEATURE_TABLE_BY_CATEGORY = 'SORT_FEATURE_TABLE_BY_CATEGORY';
export const FILTER_FEATURE_TABLE = 'FILTER_FEATURE_TABLE';
export const RESET_FEATURE_TABLE = 'RESET_FEATURE_TABLE';
export const SORT_BUG_TABLE_BY_CATEGORY = 'SORT_BUG_TABLE_BY_CATEGORY';
export const FILTER_BUG_TABLE = 'FILTER_BUG_TABLE';
export const RESET_BUG_TABLE = 'RESET_BUG_TABLE';
export const FETCH_BUG_REQUEST = 'FETCH_BUG_REQUEST';
export const FETCH_BUG_SUCCESS = 'FETCH_BUG_SUCCESS';
export const FETCH_FEATURE_SUCCESS = 'FETCH_FEATURE_SUCCESS';
export const EDIT_ETA_REQUEST = 'EDIT_ETA_REQUEST';
export const EDIT_ETA_SUCCESS = 'EDIT_ETA_SUCCESS';
export const INITIATE_CRAWLER = 'INITIATE_CRAWLER';
export const FETCH_INTERNAL_FEATURE_SUCCESS = 'FETCH_INTERNAL_FEATURE_SUCCESS';
export const FILTER_INTERNAL_FEATURE_TABLE = 'FILTER_INTERNAL_FEATURE_TABLE';
export const SET_DELETE_WARNING_BOX_STATE = 'SET_DELETE_WARNING_BOX_STATE';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
export const RESET_SELECTED_ITEM = 'RESET_SELECTED_ITEM';
export const SET_FEATURE_MODAL_STATE = 'SET_FEATURE_MODAL_STATE';

// App actions
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_TOKEN = 'SET_TOKEN';

// Data Explorer page actions
export const TOGGLE_ADD_FOLDER_MODAL = 'TOGGLE_ADD_FOLDER_MODAL';
export const ADD_NEW_FOLDER = 'ADD_NEW_FOLDER';
export const SET_FOLDER_MODAL_ERROR_MESSAGE = 'SET_FOLDER_MODAL_ERROR_MESSAGE';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const TOGGLE_UPLOAD_FILE_MODAL = 'TOGGLE_UPLOAD_FILE_MODAL';
export const CLEAR_UPLOAD_FILES_CACHE = 'CLEAR_UPLOAD_FILES_CACHE';
export const SET_UPLOAD_FILES_CACHE = 'SET_UPLOAD_FILES_CACHE';

//PTO page actions
export const SET_PTO_APPLY_MODAL_STATE = 'SET_PTO_APPLY_MODAL_STATE';
export const FILTER_PTO_TABLE = 'FILTER_PTO_TABLE';
export const SORT_PTO_TABLE_BY_CATEGORY = 'SORT_PTO_TABLE_BY_CATEGORY';
